fix: norm validation exception for global variable

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,7 +21,14 @@ jobs:
       run: pip3 install norminette
     
     - name: Run norminette
-      run: norminette
+      run: |
+        echo "Running norminette..."
+        NORM=$(norminette | grep Error:)
+        if [ -n "$NORM" ]; then
+          echo "Norminette failed!"
+          exit 1
+        fi
+        echo "Norminette passed!"
 
   compile:
     name: Compile
